### ISSUE TITLE
Add constants.py

### ISSUE THREAD

**Issue by moeyensj** [moeyensj/thor#24]
We should add a constants class that stores all relevant constants as opposed to relying on those provided by `astropy`.

**Comment by mjuric** [comment]
Are the ones in astropy incoorrect (or tend to change)?

Not opposed, just curious...

**Comment by moeyensj** [comment]
I am not sure if they are correct or incorrect, but they are different from the ones provided in the JPL ephemeris files (which is where `oorb` draws its constants from). 

For example:
```
from astropy import constants as c
from astropy import units as u

desired_units = (u.AU**3 / u.d**2)
MU_astropy = (c.G * u.M_sun).to(desired_units).value
MU_de430 = 0.295912208285591100e-3 # in units of AU^3 / d^2 from page 49 in https://ipnpr.jpl.nasa.gov/progress_report/42-196/196C.pdf

print(1 - MU_astropy/MU_de430)
3.1601721239837843e-10
```

**Comment by mjuric** [comment]
👍.

(n.b., I was curious about this, so I checked what they do: `astropy` constants do change from version to version, though there is a way to fix which version a code should use https://docs.astropy.org/en/stable/constants/, https://github.com/astropy/astropy/blob/master/astropy/constants/.)

**Comment by moeyensj** [comment]
Completed with #17
