### ISSUE TITLE
Add Python 2-body propagator

### ISSUE THREAD

**Issue by moeyensj** [moeyensj/thor#25]
Because we love Python :)

**Comment by mjuric** [comment]
May be of interest: https://github.com/cmaureir/python-kepler/blob/master/KeplerianOrbit.py

**Comment by moeyensj** [comment]
Ah, I didn't see your comment till just now. I wrote a 2-body propagator using the universal anomaly. It seems to be working! Going to clean up the code and push it.

**Comment by moeyensj** [comment]
Done with #17
