### ISSUE TITLE
worth adding clarification in README.md

### ISSUE THREAD

**Issue by suberlak** [moeyensj/thor#28]
Worth mentioning that `docker run -it moeyensj/thor:latest`  opens a virtual machine, it doesn't run the thor  code yet (for newbies in docker like me step-by-step is pretty useful :)

**Comment by moeyensj** [comment]
@suberlak I have updated the README, let me know if it is a little more clear.

**Comment by moeyensj** [comment]
Summary of discussion in person, README is more clear.
